project_id = "ixwnucfebopjqcokohhw"

[auth.hooks.send_email]
enabled = true
uri = "supabase_functions_url/auth-email"

[functions.auth-email]
verify_jwt = false
project_id = "ixwnucfebopjqcokohhw"

[functions.enhance-cv]
verify_jwt = true